+incdir+$SIM_ROOT_DIR/tools/tdb_reader
$SIM_ROOT_DIR/tools/tdb_reader/tdb_reader.a
top.sv
../../../rtl/core_top.sv
../../../rtl/fetch.sv
../../../rtl/decode.sv
../../../rtl/rename.sv
../../../rtl/readreg.sv
../../../rtl/issue.sv
../../../rtl/execute_alu.sv
../../../rtl/execute_bru.sv
../../../rtl/execute_csr.sv
../../../rtl/execute_div.sv
../../../rtl/execute_lsu.sv
../../../rtl/execute_mul.sv
../../../rtl/wb.sv
../../../rtl/commit.sv
../../../rtl/branch_predictor.sv
../../../rtl/bus.sv
../../../rtl/checkpoint_buffer.sv
../../../rtl/clint.sv
../../../rtl/csrfile.sv
../../../rtl/csr_access_check.sv
../../../rtl/data_selector.sv
../../../rtl/execute_feedback.sv
../../../rtl/interrupt_interface.sv
../../../rtl/issue_queue.sv
../../../rtl/list_enabled_item_id.sv
../../../rtl/multififo.sv
../../../rtl/phy_regfile.sv
../../../rtl/ras.sv
../../../rtl/rat.sv
../../../rtl/rob.sv
../../../rtl/store_buffer.sv
../../../rtl/tcm.sv
../../../rtl/mem_dual_port_rw.sv
../../../rtl/fifo.sv
../../../rtl/handshake_dff.sv
../../../rtl/port.sv
../../../rtl/expand_one.sv
../../../rtl/count_one.sv
../../../rtl/parallel_finder.sv
../../../rtl/priority_finder.sv
+incdir+../../../rtl